import {
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiScala,
  SiMaterialdesign,
  SiPython,
  SiDocker,
  SiJavascript,
  SiFlask,
  SiFastapi,
  SiSanity,
  SiFirebase,
  SiNuxtdotjs,
  SiStyledcomponents,
  SiVercel,
  SiVite,
  SiReactrouter,
} from 'react-icons/si';
import { FaVuejs } from 'react-icons/fa';
import { GrMysql } from 'react-icons/gr';

export const iconDict = {
  javascript: <SiJavascript />,
  typescript: <SiTypescript />,
  reactjs: <SiReact />,
  nextjs: <SiNextdotjs />,
  nuxtjs: <SiNuxtdotjs />,
  vuejs: <FaVuejs />,
  scala: <SiScala />,
  materialdesign: <SiMaterialdesign />,
  python: <SiPython />,
  mysql: <GrMysql />,
  docker: <SiDocker />,
  flask: <SiFlask />,
  fastapi: <SiFastapi />,
  sanity: <SiSanity />,
  firebase: <SiFirebase />,
  styledcomponents: <SiStyledcomponents />,
  vercel: <SiVercel />,
  vite: <SiVite />,
  reactrouter: <SiReactrouter />,
};
